### PR TITLE
Fix `Char` undefined

### PR DESCRIPTION
**Pull request by getBoolean**
The models are using the `Char` data type now, so it needs to be converted. I'm not sure what the best type to use here is because proto doesn't have a `char` type, so I put it as `int32`.

Let me know if I should use something different.

### CODE REVIEW

**Comment by BrutuZ** [comment]
> The models are using the Char data type now

I just looked at Mihon's backup models and haven't found a single instance of the Char class

**Comment by getBoolean** [comment]
I should have specified. Its being using in J2K and Yokai.

https://github.com/Jays2Kings/tachiyomiJ2K/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupCategory.kt

**Comment by getBoolean** [comment]
To add some context, I'm using the --dump-schemas command to generate the proto files and using it with the protoc Dart code generator. The protoc command is the one that throws the "`Char` is undefined" error

**Comment by BrutuZ** [comment]
I see, I'm guessing for the manual sorting that the Compose-based ones don't support.
Still, `int32` doesn't feel right, the more fitting choice would be either `string` or `bytes` given a Char is not necessarily a number https://kotlinlang.org/docs/characters.html

**Comment by getBoolean** [comment]
None of these options are perfect, but I'm leaning towards a single character string.

**Pull request merged**
